package com.lp.razorpay_clone.common.enums;

public enum WebhookEventsType {
    PAYMENT_AUTHORIZED,
    PAYMENT_CAPTURED,
    PAYMENT_FAILED,
    PAYMENT_REFUNDED,
    PAYMENT_DISPUTE_CREATED,
    PAYMENT_DISPUTE_RESOLVED,
    SUBSCRIPTION_CREATED,
    SUBSCRIPTION_CANCELLED,
    SUBSCRIPTION_PAYMENT_FAILED,
    INVOICE_CREATED,
    INVOICE_PAID,
    INVOICE_PAYMENT_FAILED
}